### ISSUE TITLE
ImportError: cannot import name _ni_support

### ISSUE THREAD

**Issue by davidoak** [rcmalli/keras-vggface#22]
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from keras.preprocessing import image
  File "/home/david/anaconda2/envs/vggface/lib/python2.7/site-packages/keras/preprocessing/image.py", line 11, in <module>
    import scipy.ndimage as ndi
  File "/home/david/anaconda2/envs/vggface/lib/python2.7/site-packages/scipy/ndimage/__init__.py", line 161, in <module>
    from .filters import *
  File "/home/david/anaconda2/envs/vggface/lib/python2.7/site-packages/scipy/ndimage/filters.py", line 35, in <module>
    from . import _ni_support
ImportError: cannot import name _ni_support
```

I have reinstall the scipy package, but same thing still happening, any ideas? Thanks

**Comment by geolauf** [comment]
Try to install scipy using Conda. (install miniconda or anaconda before)

`$ conda install scipy`
