### ISSUE TITLE
cannot import name '_obtain_input_shape'

### ISSUE THREAD

**Issue by TXien** [rcmalli/keras-vggface#46]
**Bug reports:**

  File "test.py", line 3, in <module>
    import keras_vggface
  File "/home/tung/.local/lib/python3.6/site-packages/keras_vggface/__init__.py", line 1, in <module>
    from keras_vggface.vggface import VGGFace
  File "/home/tung/.local/lib/python3.6/site-packages/keras_vggface/vggface.py", line 9, in <module>
    from keras_vggface.models import RESNET50, VGG16, SENET50
  File "/home/tung/.local/lib/python3.6/site-packages/keras_vggface/models.py", line 15, in <module>
    from keras.applications.imagenet_utils import _obtain_input_shape
ImportError: cannot import name '_obtain_input_shape'

**Code Sample:**

import keras_vggface

**Comment by pomelyu** [comment]
PR https://github.com/rcmalli/keras-vggface/pull/45 fix the issue

**Comment by Finniu** [comment]
fixed here [https://stackoverflow.com/questions/49113140/importerror-cannot-import-name-obtain-input-shape-from-keras](url)

**Comment by Catalyst-47** [comment]
I am getting this error when changing keras.applications to keras_applications
  File "D:\Anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/aravind/Desktop/Machine Learning/ML Mastery/First week/vggface_test.py", line 45, in <module>
    model = VGGFace(model='resnet50')

  File "D:\Anaconda\lib\site-packages\keras_vggface\vggface.py", line 97, in VGGFace
    classes=classes)

  File "D:\Anaconda\lib\site-packages\keras_vggface\models.py", line 232, in RESNET50
    name='conv1/7x7_s2')(img_input)

  File "D:\Anaconda\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "D:\Anaconda\lib\site-packages\keras\layers\convolutional.py", line 473, in __init__
    super(Conv2D, self).__init__(

TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by rcmalli** [comment]
This problem is already solved a long time ago. Closing it for now. Please reopen if you still have the problem.

**Comment by mikechen66** [comment]
keras_applications.imagenet_utils is deprecated 

Traceback (most recent call last):
  File "inception_v3.py", line 36, in <module>
    from keras_applications.imagenet_utils import _obtain_input_shape
ModuleNotFoundError: No module named 'keras_application

**Comment by mlewan01** [comment]
you still have to make sure that it is available in your system:

pip install keras_applications
