### ISSUE TITLE
ModuleNotFoundError: No module named 'keras.engine.topology

### ISSUE THREAD

**Issue by PierrunoYT** [rcmalli/keras-vggface#91]
Traceback (most recent call last):
  File "C:\Users\pierr\Downloads\run.py", line 3, in <module>
    import keras_vggface
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras_vggface\__init__.py", line 1, in <module>
    from keras_vggface.vggface import VGGFace
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras_vggface\vggface.py", line 9, in <module>
    from keras_vggface.models import RESNET50, VGG16, SENET50
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras_vggface\models.py", line 20, in <module>
    from keras.engine.topology import get_source_inputs
ModuleNotFoundError: No module named 'keras.engine.topology'

**Comment by o-ayoub** [comment]
@PierrunoYT  have you fixed the issue ?

**Comment by gelodefaultbrain** [comment]
This has already been solved by this issue https://github.com/rcmalli/keras-vggface/issues/73  and following a PR https://github.com/rcmalli/keras-vggface/pull/89

However I think the Pypi isn't updated yet? for some reason? I'm getting the same issue as well when I do a pip install or even pipenv install. I assume the same to you @PierrunoYT 

Could we please update Pypi please? Then we can close this? Thank you.

**Comment by gelodefaultbrain** [comment]
For now the best option is to install it on the github repo itself via

`pip install git+https://github.com/rcmalli/keras-vggface.git`
