### ISSUE TITLE
import keras_vggface raising lot of errors

### ISSUE THREAD

**Issue by sanket1203** [rcmalli/keras-vggface#98]
Following exception raised even trying to import keras_vggface

import keras_vggface
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sanketpatel/anaconda3/lib/python3.11/site-packages/keras_vggface/__init__.py", line 1, in <module>
    from keras_vggface.vggface import VGGFace
  File "/Users/sanketpatel/anaconda3/lib/python3.11/site-packages/keras_vggface/vggface.py", line 9, in <module>
    from keras_vggface.models import RESNET50, VGG16, SENET50
  File "/Users/sanketpatel/anaconda3/lib/python3.11/site-packages/keras_vggface/models.py", line 12, in <module>
    from keras.layers import Flatten, Dense, Input, GlobalAveragePooling2D, \
  File "/Users/sanketpatel/anaconda3/lib/python3.11/site-packages/keras/__init__.py", line 3, in <module>
    from keras import __internal__
  File "/Users/sanketpatel/anaconda3/lib/python3.11/site-packages/keras/__internal__/__init__.py", line 3, in <module>
    from keras.__internal__ import backend
  File "/Users/sanketpatel/anaconda3/lib/python3.11/site-packages/keras/__internal__/backend/__init__.py", line 3, in <module>
    from keras.src.backend import _initialize_variables as initialize_variables
  File "/Users/sanketpatel/anaconda3/lib/python3.11/site-packages/keras/src/__init__.py", line 21, in <module>
    from keras.src import applications
  File "/Users/sanketpatel/anaconda3/lib/python3.11/site-packages/keras/src/applications/__init__.py", line 18, in <module>
    from keras.src.applications.convnext import ConvNeXtBase
  File "/Users/sanketpatel/anaconda3/lib/python3.11/site-packages/keras/src/applications/convnext.py", line 26, in <module>
    import tensorflow.compat.v2 as tf
ModuleNotFoundError: No module named 'tensorflow'

**Comment by medined** [comment]
This command will resolve that error.

 pip install tensorflow keras_applications
 
 But then you'll see:
 
  ImportError: cannot import name 'layer_utils' from 'keras.utils' (/data/projects/visage-match/venv/lib/python3.10/site-packages/keras/utils/__init__.py)

**Comment by zodwick** [comment]
> This command will resolve that error.
> 
> pip install tensorflow keras_applications
> 
> But then you'll see:
> 
> ImportError: cannot import name 'layer_utils' from 'keras.utils' (/data/projects/visage-match/venv/lib/python3.10/site-packages/keras/utils/**init**.py)



having the same issue here, seems like keras depricated that in the newer version ( https://github.com/rcmalli/keras-vggface/issues/97 ). Couldn't get it to work though.

**Comment by Prakratijain21** [comment]
Hi, try using tensorflow 2.13.0 and pip install keras==2.12

**Comment by zodwick** [comment]
> Hi, try using tensorflow 2.13.0 and pip install keras==2.12

hey yes, something like this did work out for me. I dont remember the exact version numbers but i looked up the release dates of tf and keras and compared it with that of this repo and switched to that version. That solved my issue

**Comment by shangchengzhao** [comment]
I worked it out through a new conda env with python=3.9
`pip install keras==2.12 tensorflow numpy scipy h5py pillow six pyyaml`
`pip install git+https://github.com/rcmalli/keras-vggface.git`
`pip keras.applications`

**Comment by TajwarC** [comment]
I managed to import it by doing the following in this exact order, based on some of the replies above:

create a conda environment with python 3.9

```
pip install tensorflow==2.13.0
pip install git+https://github.com/rcmalli/keras-vggface.git
pip install keras==2.12
pip keras.applications
```

still getting errors when running ```vggface = VGGFace(model='resnet50')```

```ModuleNotFoundError: No module named 'keras.src.engine.base_layer_v1'```
